title: Assises locales pour l'Université et pour la Recherche
remote_theme: pages-themes/contrast
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

description: Présentation de la demi-journée de rencontres
